### ISSUE TITLE
chupaESRI crashes with "Invalid control character"

### ISSUE THREAD

**Issue by vielmetti** [johnjreiser/chupaESRI#2]
Here's the crash dump. I'll try to narrow down the exact record that's generating the failure. 

Suggestions for patching my way around this? 

```
Invalid control character '\n' at: line 63227 column 678 (char 1625940)
Traceback (most recent call last):
  File "./chupaESRI.py", line 266, in <module>
    jp = EsriJSON2Pg(arcjson)
  File "./chupaESRI.py", line 37, in __init__
    self.srcjson = json.loads(jsonstr)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Invalid control character '\n' at: line 63227 column 678 (char 1625940)

Failed on:  /arcgisshared/rest/services/WashCo_Dynamic/MapServer/110/query?where=objectid+>%3D+100001+AND+objectid+<%3D+101000&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson
```

**Comment by johnjreiser** [comment]
It looks like it's there are poorly encoded CRLFs in the "LEGAL_DESCRIPTION" field. 

Looks like the simplest method would be to match on \r\n and replace with \\r\\n. See: https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json

If you want to throw a re.sub in there prior to feeding the string to json.loads(), feel free to do so and then submit a pull request. If not, I'll do it later and test with the same ArcGIS Server instance.

**Comment by vielmetti** [comment]
This discussion might be relevant as well:

http://stackoverflow.com/questions/9295439/python-json-loads-error

**Comment by johnjreiser** [comment]
That layer was a perfect test case. If you git pull, incorporating the changes in https://github.com/johnjreiser/chupaESRI/commit/cc1075a3326ad23dfc6ccc4cde3ea4af1994bfa9, and then re-run the script, you should find that the data is downloaded correctly. Please verify this on your end and post back here. If everything works, I'll close the issue.

**Comment by vielmetti** [comment]
Looking good! No obvious issues as I sift through the data.

Thanks!

**Comment by vielmetti** [comment]
Thanks John. I successfully loaded 120743 records using that fix. Still sorting out how to validate that every field in every record is correct, but so far everything checks out.
